
Vagrant.configure("2") do |config|

  #config.vm.box = "base"

  #target client webserver machine
  config.vm.define "webserver" do | webserver |
    webserver.vm.box = "ubuntu/trusty32"
    webserver.vm.network "private_network", ip: "102.55.0.2"
    webserver.vm.hostname = "webserver"
  end

  #ansible command center
  config.vm.define "ansible" do | ansible |
    ansible.vm.box = "ubuntu/trusty32"
    ansible.vm.network "private_network", ip: "102.68.0.15"
    ansible.vm.hostname = "ansible"
  end

end
